%STARTUP

%% add MATPOWER paths
addpath( ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\lib', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\lib\t', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\data', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\mips\lib', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\mips\lib\t', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\most\lib', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\most\lib\t', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\mptest\lib', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\mptest\lib\t', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\extras\maxloadlim', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\extras\maxloadlim\tests', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\extras\maxloadlim\examples', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\extras\misc', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\extras\reduction', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\extras\sdp_pf', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\extras\se', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\extras\smartmarket', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\extras\state_estimator', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\extras\syngrid\lib', ...
    'C:\Users\Karam\Desktop\matpower7.0\matpower7.0\extras\syngrid\lib\t', ...
    '-end' );
